[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
getrandom = { version = "0.2", features = ["js"] }
cert = { path = "../cert" }
sha2 = "0.10.8"

[dependencies.web-sys]
version = "0.3.4"
features = []
